/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreatePatResponse struct {
	Pat *PersonalAccessToken `json:"pat,omitempty"`
	// the raw JWT token. see API documentation for details
	Token string `json:"token,omitempty"`
}
