/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ModuleValues struct {
	// the time that this resource was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	Github *ModuleValuesGithubConfig `json:"github,omitempty"`
	// the id of this resource, in UUID format
	Id string `json:"id,omitempty"`
	// Raw values (may be omitted)
	RawValues map[string]interface{} `json:"raw_values,omitempty"`
	// the time that this resource was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	Version int32 `json:"version,omitempty"`
}
