/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GithubPullRequest struct {
	GithubPullRequestBaseBranch string `json:"github_pull_request_base_branch,omitempty"`
	GithubPullRequestHeadBranch string `json:"github_pull_request_head_branch,omitempty"`
	GithubPullRequestId int64 `json:"github_pull_request_id,omitempty"`
	GithubPullRequestNumber int64 `json:"github_pull_request_number,omitempty"`
	GithubPullRequestState string `json:"github_pull_request_state,omitempty"`
	GithubPullRequestTitle string `json:"github_pull_request_title,omitempty"`
	GithubRepositoryName string `json:"github_repository_name,omitempty"`
	GithubRepositoryOwner string `json:"github_repository_owner,omitempty"`
}
