/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateMonitorRequest struct {
	CronSchedule string `json:"cron_schedule,omitempty"`
	Description string `json:"description,omitempty"`
	// Whether the monitor is disabled. In order to turn the monitor off for all modules, set disabled=true. Passing in an empty module list will trigger this monitor for all modules.
	Disabled bool `json:"disabled,omitempty"`
	Kind string `json:"kind,omitempty"`
	// A list of module ids. If empty or omitted, this monitor targets all modules.
	Modules []string `json:"modules,omitempty"`
	Name string `json:"name,omitempty"`
	PolicyBytes string `json:"policy_bytes,omitempty"`
}
