/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type RevokePatResponseExample struct {
	// the time that this resource was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// the display name for the personal access token
	DisplayName string `json:"display_name,omitempty"`
	// when the token expires
	Expires time.Time `json:"expires,omitempty"`
	// the id of this resource, in UUID format
	Id string `json:"id,omitempty"`
	// whether the token is revoked
	Revoked bool `json:"revoked,omitempty"`
	// the time that this resource was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
