/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ModuleRun struct {
	Config *ModuleRunConfig `json:"config,omitempty"`
	// the time that this resource was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	GithubPullRequest *GithubPullRequest `json:"github_pull_request,omitempty"`
	// the id of this resource, in UUID format
	Id string `json:"id,omitempty"`
	Kind string `json:"kind,omitempty"`
	MonitorResults []ModuleMonitorResult `json:"monitor_results,omitempty"`
	Monitors []ModuleMonitor `json:"monitors,omitempty"`
	Status string `json:"status,omitempty"`
	StatusDescription string `json:"status_description,omitempty"`
	// the time that this resource was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
