/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PaginationResponse struct {
	// the current page
	CurrentPage int64 `json:"current_page,omitempty"`
	// the next page
	NextPage int64 `json:"next_page,omitempty"`
	// the total number of pages for listing
	NumPages int64 `json:"num_pages,omitempty"`
}
