/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ModuleMonitor struct {
	// the time that this resource was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// the cron schedule for the monitor
	CronSchedule string `json:"cron_schedule,omitempty"`
	// the description for the monitor
	Description string `json:"description,omitempty"`
	// whether the monitor is currently disabled
	Disabled bool `json:"disabled,omitempty"`
	// the id of this resource, in UUID format
	Id string `json:"id,omitempty"`
	// whether this monitor is a default for all modules in the team
	IsDefault bool `json:"is_default,omitempty"`
	Kind string `json:"kind,omitempty"`
	// The list of modules that this monitor filters for
	Modules []string `json:"modules,omitempty"`
	// the name for the monitor
	Name string `json:"name,omitempty"`
	// the policy bytes for the monitor
	PolicyBytes string `json:"policy_bytes,omitempty"`
	// the time that this resource was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
