/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateTerraformPlanRequest struct {
	// the JSON contents of the plan
	PlanJson string `json:"plan_json"`
	// the prettified contents of the plan
	PlanPretty string `json:"plan_pretty"`
}
