/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModuleDeploymentConfig struct {
	GithubAppInstallationId string `json:"github_app_installation_id,omitempty"`
	GithubRepoBranch string `json:"github_repo_branch,omitempty"`
	GithubRepoName string `json:"github_repo_name,omitempty"`
	GithubRepoOwner string `json:"github_repo_owner,omitempty"`
	Path string `json:"path,omitempty"`
}
