/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ModuleValues struct {
	// the time that this resource was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	GithubAppInstallationId string `json:"github_app_installation_id,omitempty"`
	GithubRepoBranch string `json:"github_repo_branch,omitempty"`
	GithubRepoName string `json:"github_repo_name,omitempty"`
	GithubRepoOwner string `json:"github_repo_owner,omitempty"`
	// the id of this resource, in UUID format
	Id string `json:"id,omitempty"`
	// Github-based values
	Path string `json:"path,omitempty"`
	// the time that this resource was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Raw values (may be omitted)
	Values map[string]interface{} `json:"values,omitempty"`
	Version int32 `json:"version,omitempty"`
}
