/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiErrorBadRequestExample struct {
	// a custom Hatchet error code
	Code int32 `json:"code,omitempty"`
	// a description for this error
	Description string `json:"description,omitempty"`
	// a link to the documentation for this error, if it exists
	DocsLink string `json:"docs_link,omitempty"`
}
