/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type User struct {
	// the time that this resource was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// the display name for this user
	DisplayName string `json:"display_name,omitempty"`
	// the email address for this user
	Email string `json:"email,omitempty"`
	// whether this user's email address has been verified
	EmailVerified bool `json:"email_verified,omitempty"`
	// a URI for the user icon
	Icon string `json:"icon,omitempty"`
	// the id of this resource, in UUID format
	Id string `json:"id,omitempty"`
	// the time that this resource was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
