/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type NotificationMeta struct {
	// the time that this resource was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// the id of this resource, in UUID format
	Id string `json:"id,omitempty"`
	LastNotified time.Time `json:"last_notified,omitempty"`
	Message string `json:"message,omitempty"`
	ModuleId string `json:"module_id,omitempty"`
	NotificationId string `json:"notification_id,omitempty"`
	Resolved bool `json:"resolved,omitempty"`
	TeamId string `json:"team_id,omitempty"`
	Title string `json:"title,omitempty"`
	// the time that this resource was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
