/*
 * API v1
 *
 * # Introduction Welcome to the documentation for Hatchet's API.  
 *
 * API version: 1.0.0
 * Contact: support@hatchet.run
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateModuleValuesRequestGithub struct {
	// this refers to the Hatchet app installation id, **not** the installation id stored on Github
	GithubAppInstallationId string `json:"github_app_installation_id"`
	// the repository branch on Github
	GithubRepositoryBranch string `json:"github_repository_branch"`
	// the repository name on Github
	GithubRepositoryName string `json:"github_repository_name"`
	// the repository owner on Github
	GithubRepositoryOwner string `json:"github_repository_owner"`
	// path to the module values in the github repository (including file name)
	Path string `json:"path"`
}
